# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from displaywidget import DisplayWidget


class Ui_Window(object):
    def setupUi(self, window):
        window.setObjectName("Window")
        window.resize(339, 353)
        self.gridLayout_2 = QtWidgets.QGridLayout(window)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.displayWidget = DisplayWidget(window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.displayWidget.sizePolicy().hasHeightForWidth())
        self.displayWidget.setSizePolicy(sizePolicy)
        self.displayWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.displayWidget.setMaximumSize(QtCore.QSize(200, 200))
        self.displayWidget.setObjectName("displayWidget")
        self.gridLayout_2.addWidget(self.displayWidget, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(window)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.shapeComboBox = QtWidgets.QComboBox(window)
        self.shapeComboBox.setObjectName("shapeComboBox")
        self.shapeComboBox.addItem("")
        self.shapeComboBox.addItem("")
        self.gridLayout.addWidget(self.shapeComboBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(window)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.colorButton = QtWidgets.QToolButton(window)
        self.colorButton.setObjectName("colorButton")
        self.gridLayout.addWidget(self.colorButton, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(window)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.shapeComboBox_2 = QtWidgets.QComboBox(window)
        self.shapeComboBox_2.setObjectName("shapeComboBox_2")
        self.shapeComboBox_2.addItem("")
        self.shapeComboBox_2.addItem("")
        self.shapeComboBox_2.addItem("")
        self.gridLayout.addWidget(self.shapeComboBox_2, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.toolButton_2 = QtWidgets.QToolButton(window)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 3)
        self.label.setBuddy(self.shapeComboBox)
        self.label_2.setBuddy(self.colorButton)
        self.label_3.setBuddy(self.shapeComboBox_2)

        self.retranslateUi(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("Window", "SVG Generator"))
        self.label.setText(_translate("Window", "&Shape:"))
        self.shapeComboBox.setItemText(0, _translate("Window", "House"))
        self.shapeComboBox.setItemText(1, _translate("Window", "Car"))
        self.label_2.setText(_translate("Window", "&Color:"))
        self.colorButton.setText(_translate("Window", "Choose Color..."))
        self.label_3.setText(_translate("Window", "&Background:"))
        self.shapeComboBox_2.setItemText(0, _translate("Window", "Sky"))
        self.shapeComboBox_2.setItemText(1, _translate("Window", "Trees"))
        self.shapeComboBox_2.setItemText(2, _translate("Window", "Road"))
        self.toolButton_2.setText(_translate("Window", "Save &As..."))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QWidget()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())
